project_id = "ahqauomkgflopxgnlndd"

[functions.create-daily-room]
verify_jwt = true

[functions.create-staff-account]
verify_jwt = true

[functions.create-client-account]
verify_jwt = true

[functions.update-clinician]
verify_jwt = true

[functions.update-staff-password]
verify_jwt = true

[functions.update-staff-roles]
verify_jwt = true

[functions.extract-insurance-card]
verify_jwt = false
