project_id = "tizshsmrqqaharwpqocj"

[functions.create-client-account]
verify_jwt = true

[functions.create-staff-account]
verify_jwt = true

[functions.update-clinician]
verify_jwt = true

[functions.extract-insurance-card]
verify_jwt = false